version: '3.8'

# Les services
services:
  # Notre application node qui tourne sur le port 3000 et qui dépend de la base de données "db"
  app:
    image: node-mysql-app
    deploy:
      replicas: 3  # Nombre de réplicas souhaité pour l'application
    ports:
      - "3000:3000"
    networks:
      - app_net
    depends_on:
      - db

  # Notre base de données mysql "db" qui tourne sur le port 3306, on lui passe la configuration ainsi que le volume de base (db.sql)
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_net

# Réseaux
networks:
  app_net:

