version: '3'

services:

  app:
    image: node-mysql-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=customersdb
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  db:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql  # Utilisation d'un volume Docker pour stocker les données MySQL

volumes:
  mysql_data:  # Définition du volume Docker pour MySQL
